<?php

declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

use League\CommonMark\Environment\Environment;
use League\CommonMark\Extension\CommonMark\CommonMarkCoreExtension;
use League\CommonMark\Extension\GithubFlavoredMarkdownExtension;
use League\CommonMark\MarkdownConverter;

// ─── Markdown converter ───────────────────────────────────────────────────────

$environment = new Environment(['html_input' => 'allow', 'allow_unsafe_links' => false]);
$environment->addExtension(new CommonMarkCoreExtension());
$environment->addExtension(new GithubFlavoredMarkdownExtension());
$converter = new MarkdownConverter($environment);

// ─── Parse README.md ─────────────────────────────────────────────────────────

$readmePath = __DIR__ . '/README.md';

if (!file_exists($readmePath)) {
    fwrite(STDERR, "ERROR: README.md not found\n");
    exit(1);
}

$readme = str_replace("\r\n", "\n", (string) file_get_contents($readmePath));

/** @var array<string, array{icon: string, name: string, slug: string}> $categories */
$categories = [];

/** @var array<int, array{name: string, path: string, categorySlug: string, categoryName: string, categoryIcon: string, description: string, html: string}> $features */
$features = [];

$currentCategory = null;
$skipSections    = ['Contributing', 'Author'];

foreach (explode("\n", $readme) as $line) {
    // Category heading: ## 📊 Eloquent
    if (preg_match('/^## (.+)$/', $line, $m)) {
        $raw  = trim($m[1]);
        $skip = false;

        foreach ($skipSections as $s) {
            if (str_contains($raw, $s)) {
                $skip = true;
                break;
            }
        }

        if ($skip) {
            $currentCategory = null;
            continue;
        }

        // Extract leading emoji grapheme cluster
        $icon = '';
        if (preg_match('/^(\X)/u', $raw, $em)) {
            $icon = $em[1];
        }

        $name = trim(mb_substr($raw, mb_strlen($icon)));
        $slug = trim(strtolower((string) preg_replace('/[^a-z0-9]+/i', '-', $name)), '-');

        $currentCategory      = compact('icon', 'name', 'slug');
        $categories[$slug] ??= $currentCategory;

        continue;
    }

    if ($currentCategory === null) {
        continue;
    }

    // Feature line: - [withAggregate()](features/eloquent/withAggregate.md) — description
    if (preg_match('/^-\s+\[([^\]]+)\]\((features\/([^\/]+)\/[^)]+\.md)\)\s+[—–-]+\s+(.+)$/', $line, $m)) {
        $features[] = [
            'name'         => $m[1],
            'path'         => $m[2],
            'categorySlug' => $currentCategory['slug'],
            'categoryName' => $currentCategory['name'],
            'categoryIcon' => $currentCategory['icon'],
            'description'  => trim($m[4]),
            'html'         => '',
        ];
    }
}

// ─── Convert each .md file to HTML ───────────────────────────────────────────

foreach ($features as &$feature) {
    $file = __DIR__ . '/' . $feature['path'];

    if (!file_exists($file)) {
        fprintf(STDERR, "WARNING: %s not found\n", $feature['path']);
        continue;
    }

    $md = str_replace("\r\n", "\n", (string) file_get_contents($file));
    $md = (string) preg_replace('/\[←\s*Back to README\]\([^)]+\)/ui', '', $md);
    $md = trim($md);

    $html = (string) $converter->convert($md);
    // Strip the leading <h1> — it's already displayed in the panel header
    $html = (string) preg_replace('/<h1[^>]*>.*?<\/h1>\s*/si', '', $html, 1);
    $feature['html'] = $html;
}
unset($feature);

// ─── Build output ─────────────────────────────────────────────────────────────

$categoriesList = array_values($categories);

// Assign stable colours in PHP so JS needs no runtime lookup
$catColors = [
    'bg-blue-100 text-blue-700',
    'bg-emerald-100 text-emerald-700',
    'bg-violet-100 text-violet-700',
    'bg-amber-100 text-amber-700',
    'bg-pink-100 text-pink-700',
    'bg-sky-100 text-sky-700',
    'bg-orange-100 text-orange-700',
    'bg-teal-100 text-teal-700',
    'bg-rose-100 text-rose-700',
    'bg-indigo-100 text-indigo-700',
];

foreach ($categoriesList as $i => &$cat) {
    $cat['color'] = $catColors[$i % count($catColors)];
}
unset($cat);

printf("Building: %d features across %d categories\n", count($features), count($categoriesList));

$jsonData = json_encode(
    ['categories' => $categoriesList, 'features' => $features],
    JSON_UNESCAPED_UNICODE | JSON_HEX_TAG | JSON_THROW_ON_ERROR
);

file_put_contents(__DIR__ . '/index.html', buildHtml($jsonData));
echo "Done → index.html\n";

// ─── HTML template ────────────────────────────────────────────────────────────

function buildHtml(string $jsonData): string
{
    return <<<HTML
    <!DOCTYPE html>
    <!-- Auto-generated by build.php — do not edit manually -->
    <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>Laravel Undocumented Features</title>
      <script src="https://cdn.tailwindcss.com"></script>
      <script>
        tailwind.config = {
          theme: { extend: { colors: { laravel: '#FF2D20' }, fontFamily: { sans: ['Inter','ui-sans-serif','system-ui','sans-serif'] } } }
        }
      </script>
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" />
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github-dark.min.css" />
      <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/php.min.js"></script>
      <style>
        html, body { height: 100%; }

        /* Sidebar nav item */
        .nav-item { transition: background .12s ease, color .12s ease; }
        .nav-item.active { background: rgba(255,45,32,.08); color: #FF2D20; font-weight: 500; }
        .nav-item:not(.active):hover { background: #f3f4f6; }

        /* Markdown content */
        .md h1 { font-size: 1.5rem; font-weight: 700; color: #111827; margin-bottom: 1rem; }
        .md h2 { font-size: 1.1rem; font-weight: 600; color: #111827; margin: 1.75rem 0 .5rem; padding-bottom: .35rem; border-bottom: 1px solid #e5e7eb; }
        .md h3 { font-size: .95rem; font-weight: 600; color: #374151; margin: 1.25rem 0 .35rem; }
        .md p  { color: #4b5563; line-height: 1.8; margin-bottom: .9rem; }
        .md pre { margin: .9rem 0; border-radius: .6rem; overflow: auto; font-size: .82rem; }
        .md code:not(pre code) { background: #f3f4f6; color: #111827; padding: .15em .45em; border-radius: .3rem; font-size: .82em; font-family: monospace; }
        .md ul, .md ol { padding-left: 1.5rem; margin-bottom: .9rem; color: #4b5563; }
        .md ul { list-style: disc; }
        .md ol { list-style: decimal; }
        .md li { margin-bottom: .3rem; line-height: 1.7; }
        .md hr { border: none; border-top: 1px solid #e5e7eb; margin: 1.5rem 0; }
        .md a  { color: #FF2D20; text-decoration: underline; }
        .md strong { color: #111827; font-weight: 600; }
        .md blockquote { border-left: 3px solid #FF2D20; padding-left: 1rem; color: #6b7280; font-style: italic; margin: 1rem 0; }
        .md table { width: 100%; border-collapse: collapse; font-size: .85rem; margin-bottom: 1rem; }
        .md th { background: #f9fafb; text-align: left; padding: .5rem .75rem; border: 1px solid #e5e7eb; font-weight: 600; color: #374151; }
        .md td { padding: .5rem .75rem; border: 1px solid #e5e7eb; color: #4b5563; }

        /* Sidebar scrollbar */
        #sidebar-nav::-webkit-scrollbar { width: 3px; }
        #sidebar-nav::-webkit-scrollbar-track { background: transparent; }
        #sidebar-nav::-webkit-scrollbar-thumb { background: #e5e7eb; border-radius: 8px; }

        /* Mobile sidebar */
        #sidebar { transition: transform .25s cubic-bezier(.4,0,.2,1); }
        #mob-backdrop { opacity: 0; pointer-events: none; transition: opacity .25s ease; }
        #mob-backdrop.open { opacity: 1; pointer-events: auto; }
        @media (max-width: 1023px) {
          #sidebar { position: fixed; top: 0; left: 0; height: 100%; z-index: 40; transform: translateX(-100%); }
          #sidebar.open { transform: translateX(0); }
        }
      </style>
    </head>
    <body class="font-sans bg-gray-50" style="height:100%; display:flex; flex-direction:column;">

      <!-- Mobile top bar -->
      <header class="lg:hidden bg-[#1C1C1E] h-14 flex items-center gap-3 px-4 flex-shrink-0 z-30 relative">
        <button id="mob-toggle" class="text-white/60 hover:text-white p-1.5 rounded-lg hover:bg-white/10 transition-colors" aria-label="Toggle sidebar">
          <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/>
          </svg>
        </button>
        <span class="text-[#FF2D20] font-bold text-base tracking-tight">Laravel</span>
        <span class="text-white/20">|</span>
        <span class="text-white/80 text-sm font-medium">Undocumented Features</span>
      </header>

      <div class="flex flex-1 overflow-hidden">

        <!-- Mobile backdrop -->
        <div id="mob-backdrop" class="fixed inset-0 bg-black/40 z-30 lg:hidden"></div>

        <!-- Sidebar -->
        <aside id="sidebar" class="w-72 bg-white border-r border-gray-200 flex flex-col flex-shrink-0 lg:relative lg:translate-x-0 lg:z-auto">
          <!-- Sidebar header (desktop) -->
          <div class="hidden lg:flex bg-[#1C1C1E] h-14 px-5 items-center gap-2.5 flex-shrink-0">
            <span class="text-[#FF2D20] font-bold text-base tracking-tight">Laravel</span>
            <span class="text-white/20">|</span>
            <span class="text-white/80 text-sm font-medium">Undocumented</span>
            <a href="https://github.com/MrPunyapal/laravel-undocumented" target="_blank" rel="noopener noreferrer"
               class="ml-auto text-white/40 hover:text-white transition-colors" aria-label="GitHub">
              <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
                <path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.92.359.31.678.921.678 1.856 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd"/>
              </svg>
            </a>
          </div>

          <!-- Search -->
          <div class="px-3 py-3 border-b border-gray-100 flex-shrink-0">
            <div class="relative">
              <svg class="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-gray-400 pointer-events-none" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/>
              </svg>
              <input id="search" type="text" placeholder="Search features…"
                     class="w-full pl-8 pr-3 py-1.5 bg-gray-50 border border-gray-200 rounded-lg text-xs text-gray-800 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-[#FF2D20]/30 focus:border-[#FF2D20] focus:bg-white transition-colors" />
            </div>
          </div>

          <!-- Nav groups -->
          <nav id="sidebar-nav" class="flex-1 overflow-y-auto py-2"></nav>

          <!-- Empty search state -->
          <div id="nav-empty" class="hidden px-5 py-8 text-center text-xs text-gray-400">No features match</div>
        </aside>

        <!-- Main content -->
        <main id="main" class="flex-1 overflow-y-auto">
          <!-- Welcome / empty state -->
          <div id="welcome" class="flex flex-col items-center justify-center h-full text-center px-6 py-20">
            <div class="text-6xl mb-5">👀</div>
            <h2 class="text-xl font-bold text-gray-800 mb-2">Laravel Undocumented Features</h2>
            <p class="text-sm text-gray-500 max-w-xs">Select a feature from the sidebar to read its documentation.</p>
          </div>

          <!-- Feature content (hidden until selected) -->
          <div id="content-wrap" class="hidden px-6 sm:px-10 py-10">
            <!-- Header -->
            <div class="mb-8">
              <span id="content-badge" class="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-medium mb-4"></span>
              <h1 id="content-title" class="text-2xl font-bold text-gray-900 font-mono mb-2"></h1>
              <p id="content-desc" class="text-gray-500 text-sm leading-relaxed"></p>
            </div>
            <!-- Markdown body -->
            <div id="content-body" class="md"></div>
          </div>
        </main>

      </div>

      <script>
        var DATA = $jsonData;

        // Build slug→color lookup
        var catColor = {};
        DATA.categories.forEach(function(c) { catColor[c.slug] = c.color; });

        // Group features by category slug
        var grouped = {};
        DATA.categories.forEach(function(c) { grouped[c.slug] = []; });
        DATA.features.forEach(function(f) { grouped[f.categorySlug].push(f); });

        var searchQuery  = '';
        var searchTimer  = null;
        var activeFeature = null;

        function esc(s) {
          return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
        }

        // ─── Sidebar nav ──────────────────────────────────────────────────────

        function renderNav() {
          var nav     = document.getElementById('sidebar-nav');
          var empty   = document.getElementById('nav-empty');
          var q       = searchQuery.toLowerCase();
          var html    = '';
          var anyHit  = false;

          DATA.categories.forEach(function(cat) {
            var items = grouped[cat.slug].filter(function(f) {
              return !q
                || f.name.toLowerCase().indexOf(q) !== -1
                || f.description.toLowerCase().indexOf(q) !== -1;
            });
            if (!items.length) return;
            anyHit = true;

            html += '<div class="mb-3">';
            html += '<div class="px-4 pt-3 pb-1 text-[10px] font-semibold text-gray-400 uppercase tracking-widest select-none">'
                  + cat.icon + '&nbsp;' + esc(cat.name) + '</div>';
            items.forEach(function(f) {
              var isActive = activeFeature && activeFeature.name === f.name;
              html += '<button class="nav-item' + (isActive ? ' active' : '') + ' w-full text-left px-4 py-2 text-sm text-gray-700 flex items-center gap-2" data-name="' + esc(f.name) + '">'
                    + '<span class="truncate">' + esc(f.name) + '</span>'
                    + '</button>';
            });
            html += '</div>';
          });

          nav.innerHTML    = html;
          nav.classList.toggle('hidden', !anyHit);
          empty.classList.toggle('hidden', anyHit);

          nav.querySelectorAll('.nav-item').forEach(function(btn) {
            btn.addEventListener('click', function() {
              var name = btn.dataset.name;
              var feature = DATA.features.find(function(f) { return f.name === name; });
              if (feature) showFeature(feature);
            });
          });
        }

        // ─── Show feature ─────────────────────────────────────────────────────

        function showFeature(feature) {
          activeFeature = feature;

          // Badge
          var badge = document.getElementById('content-badge');
          badge.className = 'inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-medium mb-4 ' + catColor[feature.categorySlug];
          badge.textContent = feature.categoryIcon + ' ' + feature.categoryName;

          document.getElementById('content-title').textContent = feature.name;
          document.getElementById('content-desc').textContent  = feature.description;

          var body = document.getElementById('content-body');
          body.innerHTML = feature.html;
          body.querySelectorAll('pre code').forEach(function(b) { hljs.highlightElement(b); });

          document.getElementById('welcome').classList.add('hidden');
          document.getElementById('content-wrap').classList.remove('hidden');
          document.getElementById('main').scrollTop = 0;

          // Close mobile sidebar
          closeMobileSidebar();

          // Re-render nav to update active highlight
          renderNav();
        }

        // ─── Search ───────────────────────────────────────────────────────────

        document.getElementById('search').addEventListener('input', function(e) {
          clearTimeout(searchTimer);
          var val = e.target.value;
          searchTimer = setTimeout(function() { searchQuery = val.trim(); renderNav(); }, 150);
        });

        // ─── Mobile sidebar toggle ────────────────────────────────────────────

        var sidebar     = document.getElementById('sidebar');
        var mobBackdrop = document.getElementById('mob-backdrop');

        function closeMobileSidebar() {
          sidebar.classList.remove('open');
          mobBackdrop.classList.remove('open');
          document.body.style.overflow = '';
        }

        document.getElementById('mob-toggle').addEventListener('click', function() {
          var isOpen = sidebar.classList.toggle('open');
          mobBackdrop.classList.toggle('open', isOpen);
          document.body.style.overflow = isOpen ? 'hidden' : '';
        });

        mobBackdrop.addEventListener('click', closeMobileSidebar);

        document.addEventListener('keydown', function(e) {
          if (e.key === 'Escape') closeMobileSidebar();
        });

        // ─── Boot ─────────────────────────────────────────────────────────────

        renderNav();
      </script>
    </body>
    </html>
    HTML;
}
