<?php

declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

use League\CommonMark\Environment\Environment;
use League\CommonMark\Extension\CommonMark\CommonMarkCoreExtension;
use League\CommonMark\Extension\GithubFlavoredMarkdownExtension;
use League\CommonMark\MarkdownConverter;

// ─── Markdown converter ───────────────────────────────────────────────────────

$environment = new Environment(['html_input' => 'allow', 'allow_unsafe_links' => false]);
$environment->addExtension(new CommonMarkCoreExtension());
$environment->addExtension(new GithubFlavoredMarkdownExtension());
$converter = new MarkdownConverter($environment);

// ─── Parse README.md ─────────────────────────────────────────────────────────

$readmePath = __DIR__ . '/README.md';

if (!file_exists($readmePath)) {
    fwrite(STDERR, "ERROR: README.md not found\n");
    exit(1);
}

$readme = str_replace("\r\n", "\n", (string) file_get_contents($readmePath));

/** @var array<string, array{icon: string, name: string, slug: string}> $categories */
$categories = [];

/** @var array<int, array{name: string, path: string, categorySlug: string, categoryName: string, categoryIcon: string, description: string, html: string}> $features */
$features = [];

$currentCategory = null;
$skipSections    = ['Contributing', 'Author'];

foreach (explode("\n", $readme) as $line) {
    // Category heading: ## 📊 Eloquent
    if (preg_match('/^## (.+)$/', $line, $m)) {
        $raw  = trim($m[1]);
        $skip = false;

        foreach ($skipSections as $s) {
            if (str_contains($raw, $s)) {
                $skip = true;
                break;
            }
        }

        if ($skip) {
            $currentCategory = null;
            continue;
        }

        // Extract leading emoji grapheme cluster
        $icon = '';
        if (preg_match('/^(\X)/u', $raw, $em)) {
            $icon = $em[1];
        }

        $name = trim(mb_substr($raw, mb_strlen($icon)));
        $slug = trim(strtolower((string) preg_replace('/[^a-z0-9]+/i', '-', $name)), '-');

        $currentCategory      = compact('icon', 'name', 'slug');
        $categories[$slug] ??= $currentCategory;

        continue;
    }

    if ($currentCategory === null) {
        continue;
    }

    // Feature line: - [withAggregate()](features/eloquent/withAggregate.md) — description
    if (preg_match('/^-\s+\[([^\]]+)\]\((features\/([^\/]+)\/[^)]+\.md)\)\s+[—–-]+\s+(.+)$/', $line, $m)) {
        $features[] = [
            'name'         => $m[1],
            'path'         => $m[2],
            'categorySlug' => $currentCategory['slug'],
            'categoryName' => $currentCategory['name'],
            'categoryIcon' => $currentCategory['icon'],
            'description'  => trim($m[4]),
            'html'         => '',
        ];
    }
}

// ─── Convert each .md file to HTML ───────────────────────────────────────────

foreach ($features as &$feature) {
    $file = __DIR__ . '/' . $feature['path'];

    if (!file_exists($file)) {
        fprintf(STDERR, "WARNING: %s not found\n", $feature['path']);
        continue;
    }

    $md = str_replace("\r\n", "\n", (string) file_get_contents($file));
    $md = (string) preg_replace('/\[←\s*Back to README\]\([^)]+\)/ui', '', $md);
    $md = trim($md);

    $html = (string) $converter->convert($md);
    // Strip the leading <h1> — it's already displayed in the panel header
    $html = (string) preg_replace('/<h1[^>]*>.*?<\/h1>\s*/si', '', $html, 1);
    $feature['html'] = $html;
}
unset($feature);

// ─── Build output ─────────────────────────────────────────────────────────────

$categoriesList = array_values($categories);

// Assign stable colours in PHP so JS needs no runtime lookup
$catColors = [
    'bg-blue-100 text-blue-700',
    'bg-emerald-100 text-emerald-700',
    'bg-violet-100 text-violet-700',
    'bg-amber-100 text-amber-700',
    'bg-pink-100 text-pink-700',
    'bg-sky-100 text-sky-700',
    'bg-orange-100 text-orange-700',
    'bg-teal-100 text-teal-700',
    'bg-rose-100 text-rose-700',
    'bg-indigo-100 text-indigo-700',
];

foreach ($categoriesList as $i => &$cat) {
    $cat['color'] = $catColors[$i % count($catColors)];
}
unset($cat);

printf("Building: %d features across %d categories\n", count($features), count($categoriesList));

$jsonData = json_encode(
    ['categories' => $categoriesList, 'features' => $features],
    JSON_UNESCAPED_UNICODE | JSON_HEX_TAG | JSON_THROW_ON_ERROR
);

file_put_contents(__DIR__ . '/index.html', buildHtml($jsonData));
echo "Done → index.html\n";

// ─── HTML template ────────────────────────────────────────────────────────────

function buildHtml(string $jsonData): string
{
    return <<<HTML
    <!DOCTYPE html>
    <!-- Auto-generated by build.php — do not edit manually -->
    <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>Laravel Undocumented Features</title>
      <script src="https://cdn.tailwindcss.com"></script>
      <script>
        tailwind.config = {
          theme: { extend: { colors: { laravel: '#FF2D20' }, fontFamily: { sans: ['Inter','ui-sans-serif','system-ui','sans-serif'] } } }
        }
      </script>
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" />
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github-dark.min.css" />
      <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/php.min.js"></script>
      <style>
        /* Panel slide-in */
        #panel { transform: translateX(100%); transition: transform .28s cubic-bezier(.4,0,.2,1); }
        #panel.open { transform: translateX(0); }
        #backdrop { opacity: 0; pointer-events: none; transition: opacity .28s ease; }
        #backdrop.open { opacity: 1; pointer-events: auto; }

        /* Cards */
        .card { transition: box-shadow .15s ease, border-color .15s ease; }
        .card:hover { box-shadow: 0 6px 20px rgba(0,0,0,.08); border-color: #FF2D20 !important; }
        .card.active { border-color: #FF2D20 !important; box-shadow: 0 0 0 3px rgba(255,45,32,.12); }

        /* Markdown panel body */
        .md h2 { font-size: 1rem; font-weight: 600; color: #111827; margin: 1.4rem 0 .4rem; }
        .md p  { color: #4b5563; line-height: 1.75; margin-bottom: .8rem; }
        .md pre { margin: .8rem 0; border-radius: .5rem; overflow: auto; font-size: .8rem; }
        .md code:not(pre code) { background: #f3f4f6; color: #111827; padding: .15em .4em; border-radius: .3rem; font-size: .82em; font-family: monospace; }
        .md ul { list-style: disc; padding-left: 1.4rem; margin-bottom: .8rem; color: #4b5563; }
        .md li { margin-bottom: .2rem; line-height: 1.65; }
        .md hr { border-color: #e5e7eb; margin: 1.25rem 0; }
        .md a  { color: #FF2D20; text-decoration: underline; }
        .md strong { color: #111827; font-weight: 600; }

        /* Panel scrollbar */
        #panel-body::-webkit-scrollbar { width: 4px; }
        #panel-body::-webkit-scrollbar-track { background: transparent; }
        #panel-body::-webkit-scrollbar-thumb { background: #d1d5db; border-radius: 8px; }

        @media (max-width: 640px) { #panel { width: 100vw !important; } }
      </style>
    </head>
    <body class="font-sans bg-gray-50 min-h-screen">

      <!-- Header -->
      <header class="bg-[#1C1C1E] sticky top-0 z-30">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-14 flex items-center justify-between">
          <div class="flex items-center gap-2.5">
            <span class="text-[#FF2D20] font-bold text-lg tracking-tight">Laravel</span>
            <span class="text-white/20">|</span>
            <span class="text-white/90 font-medium text-base">Undocumented Features</span>
          </div>
          <a href="https://github.com/MrPunyapal/laravel-undocumented" target="_blank" rel="noopener noreferrer"
             class="flex items-center gap-1.5 text-white/50 hover:text-white transition-colors text-xs font-medium">
            <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
              <path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.92.359.31.678.921.678 1.856 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd"/>
            </svg>
            GitHub
          </a>
        </div>
      </header>

      <!-- Search + Filters -->
      <div class="bg-white border-b border-gray-100 sticky top-14 z-20">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-3 space-y-2.5">
          <!-- Search -->
          <div class="relative">
            <svg class="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-gray-400 pointer-events-none" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/>
            </svg>
            <input id="search" type="text" placeholder="Search features…"
                   class="w-full pl-8 pr-4 py-2 bg-gray-50 border border-gray-200 rounded-lg text-sm text-gray-800 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-[#FF2D20]/30 focus:border-[#FF2D20] focus:bg-white transition-colors" />
          </div>
          <!-- Category pills -->
          <div id="filter-scroll" class="">
            <div id="filters" class="flex flex-wrap gap-1.5 pb-0.5"></div>
          </div>
        </div>
      </div>

      <!-- Grid -->
      <main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
        <p id="count" class="text-xs text-gray-400 mb-4"></p>
        <div id="grid" class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-3"></div>
        <div id="empty" class="hidden text-center py-24">
          <div class="text-5xl mb-3">🔍</div>
          <p class="text-sm font-medium text-gray-500">No features match</p>
          <p class="text-xs text-gray-400 mt-1">Try a different search or category</p>
        </div>
      </main>

      <!-- Backdrop -->
      <div id="backdrop" class="fixed inset-0 bg-black/30 z-40"></div>

      <!-- Side Panel -->
      <aside id="panel" class="fixed top-0 right-0 h-full w-full sm:w-[500px] bg-white z-50 flex flex-col">
        <!-- Panel header -->
        <div class="bg-[#1C1C1E] px-5 py-4 flex items-start justify-between gap-4 flex-shrink-0">
          <div class="min-w-0">
            <div class="text-[#FF2D20] text-[10px] font-bold uppercase tracking-[.12em] mb-1.5" id="panel-category"></div>
            <h2 class="text-white font-bold text-lg font-mono leading-tight truncate" id="panel-title"></h2>
          </div>
          <button id="close-panel" aria-label="Close"
                  class="flex-shrink-0 mt-0.5 text-white/40 hover:text-white hover:bg-white/10 rounded-lg p-1.5 transition-colors">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/>
            </svg>
          </button>
        </div>
        <!-- Panel body -->
        <div id="panel-body" class="flex-1 overflow-y-auto">
          <div id="panel-content" class="md px-5 pt-5 pb-10"></div>
        </div>
      </aside>

      <script>
        var DATA = $jsonData;

        // Build slug→color lookup from PHP-assigned colors
        var catColor = {};
        DATA.categories.forEach(function(c) { catColor[c.slug] = c.color; });

        var activeCategory = 'all';
        var searchQuery    = '';
        var searchTimer    = null;
        var activeCard     = null;

        // Safe HTML escaping for innerHTML usage
        function esc(s) {
          return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
        }

        // ─── Filters ─────────────────────────────────────────────────────────

        function pillClass(active) {
          return active
            ? 'flex-shrink-0 px-3 py-1.5 rounded-full text-xs font-semibold bg-[#FF2D20] text-white cursor-pointer transition-all'
            : 'flex-shrink-0 px-3 py-1.5 rounded-full text-xs font-medium bg-gray-100 text-gray-600 hover:bg-gray-200 cursor-pointer transition-all';
        }

        function renderFilters() {
          var container = document.getElementById('filters');

          var html = '<button class="' + pillClass(true) + '" data-cat="all">All</button>';
          DATA.categories.forEach(function(cat) {
            html += '<button class="' + pillClass(false) + '" data-cat="' + esc(cat.slug) + '">' + cat.icon + ' ' + esc(cat.name) + '</button>';
          });
          container.innerHTML = html;

          container.addEventListener('click', function(e) {
            var btn = e.target.closest('button[data-cat]');
            if (!btn) return;
            activeCategory = btn.dataset.cat;
            container.querySelectorAll('button[data-cat]').forEach(function(b) {
              b.className = pillClass(b.dataset.cat === activeCategory);
            });
            renderGrid();
          });
        }

        // ─── Grid ─────────────────────────────────────────────────────────────

        function getFiltered() {
          var q = searchQuery.toLowerCase();
          return DATA.features.filter(function(f) {
            return (activeCategory === 'all' || f.categorySlug === activeCategory)
              && (!q || f.name.toLowerCase().indexOf(q) !== -1 ||
                  f.description.toLowerCase().indexOf(q) !== -1 ||
                  f.categoryName.toLowerCase().indexOf(q) !== -1);
          });
        }

        function renderGrid() {
          var grid     = document.getElementById('grid');
          var empty    = document.getElementById('empty');
          var filtered = getFiltered();

          document.getElementById('count').textContent = filtered.length + ' feature' + (filtered.length !== 1 ? 's' : '');

          if (!filtered.length) {
            grid.classList.add('hidden');
            empty.classList.remove('hidden');
            return;
          }

          grid.classList.remove('hidden');
          empty.classList.add('hidden');

          var html = '';
          filtered.forEach(function(feature) {
            html +=
              '<div class="card bg-white border border-gray-200 rounded-xl p-5 cursor-pointer flex flex-col gap-2.5" data-name="' + esc(feature.name) + '">' +
                '<div class="font-mono font-semibold text-sm text-gray-900">' + esc(feature.name) + '</div>' +
                '<p class="text-gray-500 text-xs leading-relaxed flex-1">' + esc(feature.description) + '</p>' +
                '<span class="self-start inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[11px] font-medium ' + catColor[feature.categorySlug] + '">' +
                  feature.categoryIcon + ' ' + esc(feature.categoryName) +
                '</span>' +
              '</div>';
          });

          grid.innerHTML = html;

          // Re-attach click handlers and restore active state
          grid.querySelectorAll('.card').forEach(function(card, i) {
            var feature = filtered[i];
            if (activeCard && activeCard.name === feature.name) card.classList.add('active');
            card.addEventListener('click', function() { openPanel(feature, card); });
          });
        }

        // ─── Panel ────────────────────────────────────────────────────────────

        var panel    = document.getElementById('panel');
        var backdrop = document.getElementById('backdrop');

        function openPanel(feature, card) {
          if (activeCard) {
            var prev = document.querySelector('.card.active');
            if (prev) prev.classList.remove('active');
          }
          activeCard = feature;
          if (card) card.classList.add('active');

          document.getElementById('panel-title').textContent    = feature.name;
          document.getElementById('panel-category').textContent = feature.categoryIcon + ' ' + feature.categoryName;

          var content = document.getElementById('panel-content');
          content.innerHTML = feature.html;
          content.querySelectorAll('pre code').forEach(function(b) { hljs.highlightElement(b); });

          panel.classList.add('open');
          backdrop.classList.add('open');
          document.body.style.overflow = 'hidden';
          document.getElementById('panel-body').scrollTop = 0;
        }

        function closePanel() {
          panel.classList.remove('open');
          backdrop.classList.remove('open');
          document.body.style.overflow = '';
          if (activeCard) {
            var prev = document.querySelector('.card.active');
            if (prev) prev.classList.remove('active');
            activeCard = null;
          }
        }

        document.getElementById('close-panel').addEventListener('click', closePanel);
        backdrop.addEventListener('click', closePanel);
        document.addEventListener('keydown', function(e) { if (e.key === 'Escape') closePanel(); });

        // ─── Search ───────────────────────────────────────────────────────────

        document.getElementById('search').addEventListener('input', function(e) {
          clearTimeout(searchTimer);
          var val = e.target.value;
          searchTimer = setTimeout(function() { searchQuery = val.trim(); renderGrid(); }, 150);
        });

        // ─── Boot ─────────────────────────────────────────────────────────────

        renderFilters();
        renderGrid();
      </script>
    </body>
    </html>
    HTML;
}
